### Create a new Movie (title,releaseDate,genre,rating,price)
POST https://dmit2015-demo-default-rtdb.firebaseio.com/movies.json
Content-Type: application/json

{
"title":"Dune",
"releaseDate": "2022-03-29",
"genre": "action",
"rating": "PG-13",
"price": 19.99
}


### Create a new Movie (title,releaseDate,genre,rating,price)
POST https://dmit2015-demo-default-rtdb.firebaseio.com/movies.json
Content-Type: application/json

{
  "title":"King Richard",
  "releaseDate": "2022-03-29",
  "genre": "comedy",
  "rating": "PG-13",
  "price": 29.99
}


### Create a new Movie (title,releaseDate,genre,rating,price)
POST https://dmit2015-demo-default-rtdb.firebaseio.com/movies.json
Content-Type: application/json

{
  "title":"Turning Red",
  "releaseDate": "2022-02-21",
  "genre": "comedy",
  "rating": "PG",
  "price": 9.99
}

### GET All Movies
GET https://dmit2015-demo-default-rtdb.firebaseio.com/movies.json

### GET One Movie by Key
GET https://dmit2015-demo-default-rtdb.firebaseio.com/movies/-MzL8GsgkaiJaQ-oMwp5.json

### UPDATE Movie and change price to 19.98 and genre to action for movie with key -MzL8GsgkaiJaQ-oMwp5
PUT https://dmit2015-demo-default-rtdb.firebaseio.com/movies/-MzL8GsgkaiJaQ-oMwp5.json
Content-Type: application/json

{
  "title":"Turning Red",
  "releaseDate": "2022-02-21",
  "genre": "action",
  "rating": "PG",
  "price": 19.98
}

### PATCH Movie and change release date to 2021-10-22 for movie with key -MzL7dqy25IRLB58OtZN
PATCH https://dmit2015-demo-default-rtdb.firebaseio.com/movies/-MzL7dqy25IRLB58OtZN.json
Content-Type: application/json

{
  "releaseDate": "2022-10-22"
}


